window.SITE_I18N={
  cs:{
    common:{brand:"Domácí IT pomoc",navServices:"Služby",navContact:"Kontakt",lang:"Jazyk"},
    home:{title:"Počítačové starosti? Přijedu zdarma a poradím — vy platíte jen za skutečnou práci.",lead:"Praktická pomoc pro domácí situace: tichý notebook, rychlejší Windows, bezpečný byt, klidné učení i pěkná prezentace nápadu."},
    services:{
      cleaning:"Váš počítač nebo notebook se přehřívá, zamrzá, nebo se zničehonic rozhučí jako vrtulník? Většinou za to nemůže stáří, ale obyčejný prach uvnitř a vyschlá teplovodivá pasta. Pečlivě vyčistím vnitřek, vyměním pastu a promažu ventilátory, aby technika opět běžela tiše a spolehlivě i v největším letním vedru. Přijedu k vám domů zdarma a první diagnostiku uděláme bez jakýchkoli závazků. Pravidelná údržba prodlouží životnost počítače klidně o několik let — a vy ušetříte za nový.",
      upgrade:"Vaše věrné PC nebo notebook už nestíhá nové programy, ale loučit se s ním ještě nechcete? Často stačí menší vylepšení a stroj naběhne jako nový. Vyměním pevný disk za rychlé SSD, přidám operační paměť, vyměním procesor nebo baterii v notebooku. Po pár hodinách práce uvidíte rozdíl od první vteřiny po zapnutí. Poradím vám zdarma, co se opravdu vyplatí — bez zbytečného přeplácení.",
      software:"Windows se vleče, vyskakují reklamy, nebo máte pocit, že počítač žije vlastním životem? Provedu kompletní úklid systému, odstraním viry i zbytečnosti a nastavím vše tak, aby to fungovalo plynule. V případě potřeby nainstaluji modernější Windows a programy pro práci, učení, zábavu i hraní. Pomohu i s registrací na úřadech, vyplněním formulářů a online žádostmi — nic, co vás dosud stresovalo, už řešit nemusíte.",
      repair:"Počítač nebo notebook dosloužil? Nevyhazujte ho hned. Často stačí vyměnit jednu jedinou součástku a technika znovu ožije za zlomek ceny nové. Posoudím, co se dá opravit, kolik to bude stát, a diagnostika je zdarma. Pokud už oprava nedává smysl, mohu starý přístroj odvézt a využít na náhradní díly — ušetříte si starosti s likvidací a možná tím pomůžete někomu dalšímu.",
      webcam:"Chcete vědět, co se děje doma, když jste v práci, nebo na zahradě a u chaty, když jste na dovolené? Připojím vám libovolný počet domácích i venkovních kamer, do kterých se podíváte kdykoli přímo z mobilu. Můžete dokonce promluvit s návštěvou na dveřích, i když právě sedíte v kanceláři. Skvělé řešení pro hlídání dětí, starších rodičů, domácích mazlíčků i chaty u lesa. Stačí, že máte internet — o zbytek se postarám.",
      alarm:"Bojíte se nezvané návštěvy, když je byt nebo garáž prázdný? Nainstaluji vám přímo na vchodové dveře dálkově ovládaný alarm s hlasitou sirénou a okamžitým upozorněním přes SMS. Skvělá ochrana pro byt, dílnu, garáž i chalupu — bez velkých stavebních zásahů a bez drahého měsíčního paušálu. Spát budete klidněji, ať jste doma, na dovolené, nebo na druhém konci světa.",
      appliances:"Moderní spotřebiče se dnes umí propojit do chytré domácnosti: světla, topení, televize, žaluzie i robotický vysavač pracují jako jeden tým. Pomohu vám vše nastavit do jediné aplikace v mobilu, abyste domov ovládali třeba i z dovolené. Vysvětlím srozumitelně, jak používat chytrou televizi a další techniku tak, aby si poradil každý člen rodiny — od dětí až po prarodiče. Pohodlí, úspora energie a hrdý pocit, že vám technika konečně slouží, ne naopak.",
      literacy:"Máte pocit, že vás moderní technika přerostla? Naučím vás od úplných základů pracovat s počítačem a využívat nové nástroje včetně umělé inteligence. Ukážu, jak si bezpečně zařídit e-mail, e-banking, nakupovat online, volat s vnoučaty přes video, nebo si nechat poradit od AI s každodenními úkoly. Tempo přizpůsobím vám — bez stresu, bez cizích slov a bez pocitu, že se ptáte na hloupost.",
      tutor:"Hledáte doučování informatiky pro své dítě? Mám vysokoškolské IT vzdělání a zkušenosti s výukou studentů ještě z doby doktorského studia. Látku ze školy vysvětlím srozumitelně, pomohu s domácími úkoly i s přípravou na přijímačky a maturitu. Z předmětu, kterého se dítě dosud bálo, se snadno může stát ten nejoblíbenější — a otevřít cestu k dobře placené budoucí profesi.",
      chess:"Šachy jsou jeden z nejlepších tréninků logického myšlení, trpělivosti a sebedůvěry — a navíc se hodí na celý život. Hraji na velmi dobré úrovni a rád své zkušenosti předám dětem i dospělým začátečníkům. Pravidelná hra zlepšuje soustředění ve škole i v práci a baví celou rodinu při společných večerech. Možná je to přesně ta jiskra, která vašemu dítěti dosud chyběla.",
      development:"Chcete, aby vaše dítě bylo o krok napřed před ostatními? Naučím ho používat umělou inteligenci chytře — tak, aby mu pomáhala s úkoly, projekty i s pochopením složitějších předmětů. Místo bezcílného surfování po mobilu objeví, jak technologii skutečně využít. Můžeme se učit hravou formou jako volnočasový kroužek, nebo přímo nad domácími úkoly. Investice do schopností, které mu pomohou v jakékoli budoucí profesi.",
      design:"Potřebujete dát svému podnikání nebo nápadu pěknou tvář? Jsem diplomovaný vývojář softwaru a vytvořím pro vás stylové letáky, plakáty, webové stránky, katalogy zboží i celé aplikace na míru. Vše srozumitelně, bez prázdných marketingových frází a s důrazem na to, aby to opravdu přitahovalo zákazníky. Stačí zavolat a popsat svůj nápad — návrh připravíme společně.",
      contact:"Zavolejte nebo napište kdykoli — první návštěva i diagnostika jsou vždy zdarma a bez závazků. Společně najdeme to nejjednodušší řešení přímo u vás doma."
    }
  }
};
